Feature 3 sap session controller
Metatavu/pakkasmarja-erp-services pull request #4
Opened 2022-02-10 11:47 UTC by platonovsimeon

Resolves #3

2022-02-10 13:03 UTC, anttileppa requested changes

2022-02-10 13:03 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/pakkasmarja/services/erp/sap/session/SapSessionController.kt
> +        val cookies = headers.allValues("set-cookie") ?: throw SapSessionLoginException("'set-cookie' not found")
Parse cookie properly with HttpCookie.parse instead of using startsWith, split etc.

2022-02-10 13:03 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/pakkasmarja/services/erp/sap/session/SapSessionLoginException.kt
> +class SapSessionLoginException(message: String): Exception(message) {
Add docs

2022-02-10 13:03 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/pakkasmarja/services/erp/sap/session/SapSessionLogoutException.kt
> +class SapSessionLogoutException(message: String): Exception(message) {
Add docs

2022-02-10 13:36 UTC, platonovsimeon commented on src/main/kotlin/fi/metatavu/pakkasmarja/services/erp/sap/session/SapSession.kt
> +class SapSession(val apiUrl: String, val routeId: String, val sessionId: String): Closeable {
Fixed

2022-02-11 07:36 UTC, platonovsimeon commented on src/main/kotlin/fi/metatavu/pakkasmarja/services/erp/sap/session/SapSessionController.kt
> +            val jsonString = objectMapper.writeValueAsString(loginInfo)
Using now byte arrays

2022-02-11 07:36 UTC, platonovsimeon commented on src/main/kotlin/fi/metatavu/pakkasmarja/services/erp/sap/session/SapSessionLoginException.kt
> +class SapSessionLoginException(message: String): Exception(message) {
Added

2022-02-11 07:36 UTC, platonovsimeon commented on src/main/kotlin/fi/metatavu/pakkasmarja/services/erp/sap/session/SapSessionLogoutException.kt
> +class SapSessionLogoutException(message: String): Exception(message) {
Added

2022-02-11 12:14 UTC, merged